### ISSUE TITLE
Setting invocations on experiment has no effect.

### ISSUE THREAD

**Issue by smarr** [smarr/ReBench#112]
The following example executes for 1 invocation instead of 10:

```yaml
experiments:
    steady:
        invocations: 10
        executions:
            - Java:
                suites:
                    - java-awfy-steady
```

I assume that somewhere the handling of defaults interferes with picking up the settings, or the settings are not yet correctly read.
