### ISSUE TITLE
ReBench reports fail while JMH runs succeed

### ISSUE THREAD

**Issue by qinsoon** [smarr/ReBench#146]
I am trying to run some micro benchmarks with JMH. However, I believe the benchmark runs succeeded with JMH but ReBench reported a failure. Is there anything that I missed?

My configuration:
```
# this run definition will be chosen if no parameters are given to rebench
default_experiment: all

# a set of suites with different benchmarks and possibly different settings
benchmark_suites:
    BenchmarkGames:
        gauge_adapter: JMH
        command: -jar target/benchmarks.jar %(benchmark)s
        benchmarks:
            - BinaryTrees

# a set of executables for the benchmark execution
executors:
    DefaultJVM:
        executable: java

# combining benchmark suites and executions
experiments:
    Test:
        data_file: 'benchmark_games.data'
        suites:
          - BenchmarkGames
        executions:
            - DefaultJVM
```

and the output is as below:
```
$ rebench microbm.conf -d --quick
Error: Process niceness can not be set.
    To execute benchmarks with highest priority,
    you might need root/admin rights.
    Deactivated usage of nice command.
ReBenchDB enabled: False

Executing run:BinaryTrees (DefaultJVM, BenchmarkGames) 1 None None
    cmd: java -jar target/benchmarks.jar BinaryTrees
    cwd: /home/yilin/Code/ci-perf-kit/microbm
    Starting run
# JMH version: 1.25.1
# VM version: JDK 1.8.0_265, OpenJDK 64-Bit Server VM, 25.265-b01
# VM invoker: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
# VM options: <none>
# Warmup: 5 iterations, 10 s each
# Measurement: 5 iterations, 10 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: org.mmtk.microbm.benchmark_games.BinaryTrees.run
# Parameters: (depth = 21)

# Run progress: 0.00% complete, ETA 00:08:20
# Fork: 1 of 5
# Warmup Iteration   1: 1.397 s/op
# Warmup Iteration   2: 1.375 s/op
# Warmup Iteration   3: 1.372 s/op
# Warmup Iteration   4: 1.380 s/op
# Warmup Iteration   5: 1.373 s/op
Iteration   1: 1.378 s/op
Iteration   2: 1.386 s/op
Iteration   3: 1.385 s/op
Iteration   4: 1.362 s/op
Iteration   5: 1.380 s/op

# Run progress: 20.00% complete, ETA 00:07:22
# Fork: 2 of 5
# Warmup Iteration   1: 1.403 s/op
# Warmup Iteration   2: 1.374 s/op
# Warmup Iteration   3: 1.387 s/op
# Warmup Iteration   4: 1.365 s/op
# Warmup Iteration   5: 1.371 s/op
Iteration   1: 1.369 s/op
Iteration   2: 1.377 s/op
Iteration   3: 1.368 s/op
Iteration   4: 1.377 s/op
Iteration   5: 1.364 s/op

# Run progress: 40.00% complete, ETA 00:05:31
# Fork: 3 of 5
# Warmup Iteration   1: 1.401 s/op
# Warmup Iteration   2: 1.389 s/op
# Warmup Iteration   3: 1.372 s/op
# Warmup Iteration   4: 1.379 s/op
# Warmup Iteration   5: 1.379 s/op
Iteration   1: 1.379 s/op
Iteration   2: 1.364 s/op
Iteration   3: 1.365 s/op
Iteration   4: 1.368 s/op
Iteration   5: 1.370 s/op

# Run progress: 60.00% complete, ETA 00:03:40
# Fork: 4 of 5
# Warmup Iteration   1: 1.399 s/op
# Warmup Iteration   2: 1.391 s/op
# Warmup Iteration   3: 1.375 s/op
# Warmup Iteration   4: 1.376 s/op
# Warmup Iteration   5: 1.379 s/op
Iteration   1: 1.387 s/op
Iteration   2: 1.370 s/op
Iteration   3: 1.386 s/op
Iteration   4: 1.370 s/op
Iteration   5: 1.397 s/op

# Run progress: 80.00% complete, ETA 00:01:50
# Fork: 5 of 5
# Warmup Iteration   1: 1.397 s/op
# Warmup Iteration   2: 1.384 s/op
# Warmup Iteration   3: 1.377 s/op
# Warmup Iteration   4: 1.386 s/op
# Warmup Iteration   5: 1.372 s/op
Iteration   1: 1.380 s/op
Iteration   2: 1.370 s/op
Iteration   3: 1.380 s/op
Iteration   4: 1.373 s/op
Iteration   5: 1.372 s/op


Result "org.mmtk.microbm.benchmark_games.BinaryTrees.run":
  1.375 ±(99.9%) 0.007 s/op [Average]
  (min, avg, max) = (1.362, 1.375, 1.397), stdev = 0.009
  CI (99.9%): [1.369, 1.382] (assumes normal distribution)


# Run complete. Total time: 00:09:12

REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
experiments, perform baseline and negative tests that provide experimental control, make sure
the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
Do not assume the numbers tell you what you want them to tell.

Benchmark        (depth)  Mode  Cnt  Score   Error  Units
BinaryTrees.run       21  avgt   25  1.375 ± 0.007   s/op
    Execution has failed, benchmark is aborted.
        The benchmark failed 1 times in a row.


------------------------------------------------------------------------------------------------
  Benchmark     Executor     Suite            Extra   Core   Size   Var   #Samples   Mean (ms)  
------------------------------------------------------------------------------------------------
  BinaryTrees   DefaultJVM   BenchmarkGames              1                       0   Failed     
------------------------------------------------------------------------------------------------

```
