### ISSUE TITLE
Support for passing on Environment variables

### ISSUE THREAD

**Issue by krono** [smarr/ReBench#42]
It would be nice to pass on environment variables to the binary/vm
- on a per-binary basis
- on a per-benchmark basis
- on a per-suite basis
- on a per-experiment basis (and so on)

**Comment by smarr** [comment]
Based on a discussion with @charig:

I could imagine support for environment variables like this:

```
MyBenchmark:
  command: foobar
  env:
    MY_VAR: %(input)s
    BAZ: sdfsdfsdf
```

It might be good to simply add it to `EXP_RUN_DETAILS` here https://github.com/smarr/ReBench/blob/master/rebench/rebench-schema.yml#L6

This way, there are plenty of places where it could be adapted.
Though, there is some conceptual mismatch between what's there already and the env settings.
So, it may as well go simply to VM and suite.
